remove kind

diff --git a/ci/multicluster/Jenkinsfile b/ci/multicluster/Jenkinsfile
--- a/ci/multicluster/Jenkinsfile
+++ b/ci/multicluster/Jenkinsfile
@@ -4,11 +4,8 @@
 def DOCKER_IMAGE_TAG
 def SKIP_ACCEPTANCE_TESTS = false
 def EFFECTIVE_DUMP_K8S_CLUSTER_ON_SUCCESS = false
-def availableRegions = [ "ap-chuncheon-1", "ap-hyderabad-1", "ap-melbourne-1", "ap-mumbai-1", "ap-osaka-1", "ap-seoul-1", "ap-sydney-1",
-                          "ap-tokyo-1", "ca-montreal-1", "ca-toronto-1", "eu-amsterdam-1", "eu-frankfurt-1", "eu-zurich-1", "me-jeddah-1",
-                          "sa-saopaulo-1", "uk-london-1" ]
+def availableRegions = [ "ap-tokyo-1" ]
 def acmeEnvironments = [ "staging", "production" ]
-Collections.shuffle(availableRegions)
 def zoneId = UUID.randomUUID().toString().substring(0,6).replace('-','')
 def dns_zone_ocid = 'dummy'
 def OKE_CLUSTER_PREFIX = ""
@@ -36,7 +33,7 @@ pipeline {
         booleanParam (description: 'Whether to use External Elasticsearch', name: 'EXTERNAL_ELASTICSEARCH', defaultValue: false)
         choice (description: 'Number of Cluster', name: 'TOTAL_CLUSTERS', choices: ["2", "1", "3"])
         choice (description: 'Verrazzano Test Environment', name: 'TEST_ENV',
-                choices: ["kind", "magicdns_oke", "ocidns_oke"])
+                choices: ["magicdns_oke", "ocidns_oke"])
         choice (description: 'ACME Certificate Environment (Staging or Production)', name: 'ACME_ENVIRONMENT',
                 choices: acmeEnvironments)
         choice (description: 'OCI region to launch OKE clusters', name: 'OKE_CLUSTER_REGION',
@@ -49,10 +46,6 @@ pipeline {
                 description: 'Kubernetes Version for OKE Cluster',
                 // 1st choice is the default value
                 choices: [ "v1.20.8", "v1.18.10", "v1.19.7", "v1.19.12" ])
-        choice (name: 'KIND_CLUSTER_VERSION',
-                description: 'Kubernetes Version for KIND Cluster',
-                // 1st choice is the default value
-                choices: [ "1.20", "1.19", "1.21" ])
         string (name: 'VERSION_FOR_INSTALL',
                 defaultValue: 'v1.0.0',
                 description: 'This is the Verrazzano version for install before doing an upgrade.  By default, the v1.0.0 release will be installed',
@@ -188,7 +181,6 @@ pipeline {
         OCI_CLI_REGION = "${params.OKE_CLUSTER_REGION}"
         OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING = 'True'
 
-        INSTALL_CONFIG_FILE_KIND = "${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts/install-verrazzano-kind-with-persistence.yaml"
         INSTALL_CONFIG_FILE_OCIDNS = "${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts/install-verrazzano-ocidns.yaml"
         INSTALL_CONFIG_FILE_NIPIO = "${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts/install-verrazzano-nipio.yaml"
         OCI_DNS_ZONE_NAME="z${zoneId}.v8o.io"
@@ -218,7 +210,7 @@ pipeline {
         // used to emit metrics
         PROMETHEUS_GW_URL = credentials('prometheus-dev-url')
         TEST_ENV_LABEL = "${params.TEST_ENV}"
-        K8S_VERSION_LABEL = "${params.TEST_ENV == 'kind' ? params.KIND_CLUSTER_VERSION : params.OKE_CLUSTER_VERSION}"
+        K8S_VERSION_LABEL = "${params.OKE_CLUSTER_VERSION}"
 
         // sample app deployed before upgrade and UI console tests
         SAMPLE_APP_NAME="hello-helidon-appconf"
@@ -314,11 +306,7 @@ pipeline {
                     // update the description with some meaningful info
                     setDisplayName()
                     currentBuild.description = SHORT_COMMIT_HASH + " : " + env.GIT_COMMIT + " : " + params.GIT_COMMIT_TO_USE
-
-                    if (params.TEST_ENV != "kind") {
-                        // derive the prefix for the OKE cluster
-                        OKE_CLUSTER_PREFIX = sh(returnStdout: true, script: "${GO_REPO_PATH}/verrazzano/ci/scripts/derive_oke_cluster_name.sh").trim()
-                    }
+                    OKE_CLUSTER_PREFIX = sh(returnStdout: true, script: "${GO_REPO_PATH}/verrazzano/ci/scripts/derive_oke_cluster_name.sh").trim()
                 }
             }
         }
@@ -336,12 +324,6 @@ pipeline {
             stages {
                 stage('Prepare AT environment') {
                     parallel {
-                        stage('Create Kind Clusters') {
-                            when { expression { return params.TEST_ENV == 'kind' } }
-                            steps {
-                                createKindClusters()
-                            }
-                        }
                         stage('Create OKE Clusters') {
                             when { expression { return params.TEST_ENV == 'ocidns_oke' || params.TEST_ENV == 'magicdns_oke'} }
                             environment {
@@ -462,12 +444,6 @@ pipeline {
                                         }
                                     }
                                 }
-                            }
-                        }
-                        stage("Configure KinD") {
-                            when { expression { return params.TEST_ENV == 'kind' } }
-                            steps {
-                                configureVerrazzanoInstallers(env.INSTALL_CONFIG_FILE_KIND,"./tests/e2e/config/scripts/process_kind_install_yaml.sh", params.WILDCARD_DNS_DOMAIN)
                             }
                         }
                         stage("Configure OKE/MagicDNS") {
@@ -659,30 +635,19 @@ pipeline {
                 }
 
                 int clusterCount = params.TOTAL_CLUSTERS.toInteger()
-                if (env.TEST_ENV == "kind") {
-                    for(int count=1; count<=clusterCount; count++) {
-                        sh """
-                            if [ "${env.TEST_ENV}" == "kind" ]
-                            then
-                                kind delete cluster --name ${CLUSTER_NAME_PREFIX}-$count
-                            fi
-                        """
-                    }
-                } else {
+                sh """
+                    mkdir -p ${KUBECONFIG_DIR}
+                    if [ "${TEST_ENV}" == "ocidns_oke" ]; then
+                        cd ${GO_REPO_PATH}/verrazzano
+                        ./tests/e2e/config/scripts/oci_dns_ops.sh -o delete -s z${zoneId} || echo "Failed to delete DNS zone z${zoneId}"
+                    fi
+                """
+                for(int count=1; count<=clusterCount; count++) {
                     sh """
-                        mkdir -p ${KUBECONFIG_DIR}
-                        if [ "${TEST_ENV}" == "ocidns_oke" ]; then
-                          cd ${GO_REPO_PATH}/verrazzano
-                          ./tests/e2e/config/scripts/oci_dns_ops.sh -o delete -s z${zoneId} || echo "Failed to delete DNS zone z${zoneId}"
-                        fi
+                        cd ${TEST_SCRIPTS_DIR}
+                        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                        TF_VAR_label_prefix=${OKE_CLUSTER_PREFIX}-$count TF_VAR_state_name=${env.BUILD_NUMBER}-${env.TIMESTAMP}-${env.BRANCH_NAME}-$count ./delete_oke_cluster.sh $count
                     """
-                    for(int count=1; count<=clusterCount; count++) {
-                        sh """
-                            cd ${TEST_SCRIPTS_DIR}
-                            export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-                            TF_VAR_label_prefix=${OKE_CLUSTER_PREFIX}-$count TF_VAR_state_name=${env.BUILD_NUMBER}-${env.TIMESTAMP}-${env.BRANCH_NAME}-$count ./delete_oke_cluster.sh $count
-                        """
-                    }
                 }
                 sh """
                     if [ -f ${POST_DUMP_FAILED_FILE} ]; then
@@ -697,52 +662,6 @@ pipeline {
             deleteDir()
         }
     }
-}
-
-// Create a KinD cluster instance
-// - count - the cluster index into $KUBECONFIG_DIR
-// - metallbAddressRange - the address range to provide the Metallb install within the KinD Docker bridge network address range
-// - cleanupKindContainers - indicates to the script whether or not to remove any existing clusters with the same name before creating the new one
-// - connectJenkinsRunnerToNetwork - indicates whether or not to connect the KinD Docker bridge network to the Jenkins local docker network
-def installKindCluster(count, metallbAddressRange, cleanupKindContainers, connectJenkinsRunnerToNetwork) {
-    // For parallel execution, wrap this in a Groovy enclosure {}
-     return script {
-            sh """
-                echo ${CLUSTER_NAME_PREFIX}-$count
-                echo ${KUBECONFIG_DIR}/$count/kube_config
-                mkdir -p ${KUBECONFIG_DIR}/$count
-                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-                echo "Create Kind cluster \$1"
-                cd ${TEST_SCRIPTS_DIR}
-                # As a stop gap, for now we are using the api/vpo caches here to see if it helps with rate limiting issues, we will need to add specific caches so for now
-                # specify the cache name based on the count value, this is assuming 1 or 2 clusters
-                case "${count}" in
-                    1)
-                        ./create_kind_cluster.sh "${CLUSTER_NAME_PREFIX}-$count" "${GO_REPO_PATH}/verrazzano/platform-operator" "${KUBECONFIG_DIR}/$count/kube_config" "${params.KIND_CLUSTER_VERSION}" "$cleanupKindContainers" "$connectJenkinsRunnerToNetwork" true ${params.CREATE_CLUSTER_USE_CALICO} "vpo_integ"
-                        ;;
-                    2)
-                        ./create_kind_cluster.sh "${CLUSTER_NAME_PREFIX}-$count" "${GO_REPO_PATH}/verrazzano/platform-operator" "${KUBECONFIG_DIR}/$count/kube_config" "${params.KIND_CLUSTER_VERSION}" "$cleanupKindContainers" "$connectJenkinsRunnerToNetwork" true ${params.CREATE_CLUSTER_USE_CALICO} "apo_integ"
-                        ;;
-                    *)
-                        ./create_kind_cluster.sh "${CLUSTER_NAME_PREFIX}-$count" "${GO_REPO_PATH}/verrazzano/platform-operator" "${KUBECONFIG_DIR}/$count/kube_config" "${params.KIND_CLUSTER_VERSION}" "$cleanupKindContainers" "$connectJenkinsRunnerToNetwork" false ${params.CREATE_CLUSTER_USE_CALICO} "NONE"
-                        ;;
-                esac
-                if [ ${params.CREATE_CLUSTER_USE_CALICO} == true ]; then
-                    echo "Install Calico"
-                    cd ${GO_REPO_PATH}/verrazzano
-                    ./ci/scripts/install_calico.sh "${CLUSTER_NAME_PREFIX}-$count"
-                fi
-                kubectl wait --for=condition=ready nodes/${CLUSTER_NAME_PREFIX}-$count-control-plane --timeout=5m
-                kubectl wait --for=condition=ready pods/kube-controller-manager-${CLUSTER_NAME_PREFIX}-$count-control-plane -n kube-system --timeout=5m
-                echo "Listing pods in kube-system namespace ..."
-                kubectl get pods -n kube-system
-                echo "Install metallb"
-                cd ${GO_REPO_PATH}/verrazzano
-                ./tests/e2e/config/scripts/install-metallb.sh $metallbAddressRange
-                echo "Deploy external es and create its secret on the admin cluster if EXTERNAL_ELASTICSEARCH is true"
-                CLUSTER_NUMBER=${count}  ./tests/e2e/config/scripts/create-external-es.sh
-            """
-        }
 }
 
 // Either download the specified release of the platform operator YAML, or create one
@@ -1108,41 +1027,6 @@ def configureVerrazzanoInstallers(installResourceTemplate, configProcessorScript
     }
 }
 
-// Create the required KinD clusters
-def createKindClusters() {
-    script {
-        sh """
-            echo "tests will execute" > ${TESTS_EXECUTED_FILE}
-        """
-        // NOTE: Eventually we should be able to parallelize the cluster creation, however
-        // we seem to be getting some kind of timing issue on cluster create; the 2nd
-        // cluster always seems to get a connect/timeout issue, so for now we are keeping
-        // the KinD cluster creation serial
-
-        // Can these for now, but eventually we should be able to build this based on
-        // inspecting the Docker bridge network CIDR and splitting up a range based on
-        // the cluster count.
-
-        def addressRanges = [ "172.18.0.231-172.18.0.238", "172.18.0.239-172.18.0.246", "172.18.0.247-172.18.0.254"]
-        def clusterInstallStages = [:]
-        boolean cleanupKindContainers = true
-        boolean connectJenkinsRunnerToNetwork = true
-        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
-        for(int count=1; count<=clusterCount; count++) {
-            string metallbAddressRange = addressRanges.get(count-1)
-            def deployStep = "cluster-${count}"
-            // Create dictionary of steps for parallel execution
-            //clusterInstallStages[deployStep] = installKindCluster(count, metallbAddressRange, cleanupKindContainers, connectJenkinsRunnerToNetwork)
-            // For sequential execution of steps
-            installKindCluster(count, metallbAddressRange, cleanupKindContainers, connectJenkinsRunnerToNetwork)
-            cleanupKindContainers = false
-            connectJenkinsRunnerToNetwork = false
-        }
-        // Execute steps in parallel
-        //parallel clusterInstallStages
-    }
-}
-
 def createOKEClusters(clusterPrefix) {
     script {
             int clusterCount = params.TOTAL_CLUSTERS.toInteger()
@@ -1368,7 +1252,7 @@ def metricJobName(stageName) {
 
 // Construct the set of labels/dimensions for the metrics
 def getMetricLabels() {
-    def kube_ver = "${params.TEST_ENV == 'kind' ? params.KIND_CLUSTER_VERSION : params.OKE_CLUSTER_VERSION }"
+    def kube_ver = "${ params.OKE_CLUSTER_VERSION }"
     def buildNumber = String.format("%010d", env.BUILD_NUMBER.toInteger())
     labels = 'build_number=\\"' + "${buildNumber}"+'\\",' +
              'jenkins_build_number=\\"' + "${env.BUILD_NUMBER}"+'\\",' +
